version: "3"
services:
  # 如果需要多账号并发请求，可以新建一行asm_unicom 然后拷贝asm_unicom下面的代码，并修改container_name,hostname方便管理
  asm_unicom:
    image: xclamp/asm-wrapper:unicomless
    container_name: asm_unicom
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: asm
    volumes:
      - ./config:/AutoSignMachine/scripts/config
      - ./cookies:/root/.AutoSignMachine
      - ./logs:/AutoSignMachine/logs #同步脚本地址
    environment:
      - ENABLE_UNICOM=true #签到开关 false / true
      - KEY=
      - REPO_URL=
      - ASM_SCRIPTS_BRANCH=
      - notify_tele_bottoken=
      - notify_tele_chatid=
